<template>
  <div
    v-if="loadingData"
    class="d-flex justify-center align-center w-screen h-screen"
  >
    <div class="loadingio-spinner-eclipse-ui0s8haubu">
      <div class="ldio-y76dksaydk">
        <div></div>
      </div>
    </div>
  </div>
  <!-- <div v-else>oida</div> -->
  <router-view v-else />
</template>

<script setup lang="ts">
import { onBeforeMount, ref } from "vue";
import useAuth from "@/hooks/useAuth";
import { useStorageStore } from "./store/storageStore";
import { storeToRefs } from "pinia";

const { loadingData } = storeToRefs(useStorageStore());
const { initAll } = useStorageStore();

onBeforeMount(async () => {
  const { initAuth } = useAuth();
  initAuth();
  await initAll();
});
</script>

<style type="text/css">
@keyframes ldio-y76dksaydk {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-y76dksaydk div {
  position: absolute;
  animation: ldio-y76dksaydk 1s linear infinite;
  width: 188px;
  height: 188px;
  top: 6px;
  left: 6px;
  border-radius: 50%;
  box-shadow: 0 5.6000000000000005px 0 0 #5f2a62;
  transform-origin: 94px 96.8px;
}
.loadingio-spinner-eclipse-ui0s8haubu {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-y76dksaydk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-y76dksaydk div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
