<template>
  <v-app id="nebula">
    <v-app-bar flat :image="nebulaBg" elevation="10">
      <v-container class="fill-height d-flex align-center justify-center pa-0">
        <v-avatar :image="nebulaLogo" size="48"></v-avatar>

        <v-btn
          v-for="link in links"
          :key="link.title"
          variant="text"
          color="white"
          @click="$router.push(link.to)"
          :class="xs ? 'pa-0' : ''"
          size="x-large"
        >
          {{ link.title }}
        </v-btn>

        <v-menu>
          <template v-slot:activator="{ props }">
            <v-btn
              :class="smAndDown ? '' : 'd-none'"
              v-bind="props"
              icon="mdi-menu"
              variant="elevated"
              color="white"
            ></v-btn>
          </template>
          <Sidebar />
        </v-menu>
      </v-container>
    </v-app-bar>

    <v-main
      :class="trainingStatus ? 'mainMarginBottomForTrainingBar' : ''"
      class="bg-deep-purple-lighten-5"
    >
      <!-- <v-toolbar
        class="bg-white pl-6"
        :border="true"
        :class="smAndDown ? '' : 'd-none'"
        title="Menu"
        :collapse="xs"
      >
      </v-toolbar> -->
      <v-container>
        <v-row>
          <v-col :cols="md ? 4 : 3" :hidden="smAndDown" class="fixed">
            <Sidebar />
          </v-col>

          <v-col>
            <v-sheet min-height="70vh" rounded="lg" elevation="20">
              <div
                v-if="loadingData"
                class="d-flex justify-center align-center w-screen h-screen"
              >
                <div class="loadingio-spinner-eclipse-ui0s8haubu">
                  <div class="ldio-y76dksaydk">
                    <div></div>
                  </div>
                </div>
              </div>
              <router-view v-else />
            </v-sheet>
          </v-col>
        </v-row>
      </v-container>
    </v-main>

    <TrainingBar v-if="trainingStatus" />
    <CustomSnackbar
      v-model="snackbarOpen"
      :text="snackbarText"
      :color="snackbarColor"
    />
  </v-app>
</template>

<script setup lang="ts">
import Sidebar from "@/components/menu/Sidebar.vue";
import CustomSnackbar from "@/components/generic/CustomSnackbar.vue";
import { useDisplay } from "vuetify";
import nebulaLogo from "@/assets/logo.svg";
import nebulaBg from "@/assets/bg/appBarNebula.jpg";
import { storeToRefs } from "pinia";
import TrainingBar from "@/components/menu/TrainingBar.vue";
import { useTrainingStore } from "@/store/trainingStore";
import { useStorageStore } from "@/store/storageStore";
import { onBeforeMount } from "vue";
import { useSnackbarStore } from "@/store/snackbarStore";

const { smAndDown, xs, md } = useDisplay();
const { snackbarOpen, snackbarText, snackbarColor } = storeToRefs(
  useSnackbarStore()
);
const { trainingStatus } = storeToRefs(useTrainingStore());

const { loadingData } = storeToRefs(useStorageStore());
const { initAll } = useStorageStore();

onBeforeMount(async () => {
  await initAll();
});

const links = [
  {
    title: "Nebula",
    to: "/",
  },
  {
    title: "About",
    to: "/about",
  },
];
</script>

<style scoped type="text/css">
.mainMarginBottomForTrainingBar {
  margin-bottom: 5rem;
}

@keyframes ldio-y76dksaydk {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-y76dksaydk div {
  position: absolute;
  animation: ldio-y76dksaydk 1s linear infinite;
  width: 188px;
  height: 188px;
  top: 6px;
  left: 6px;
  border-radius: 50%;
  box-shadow: 0 5.6000000000000005px 0 0 #673ab7;
  transform-origin: 94px 96.8px;
}
.loadingio-spinner-eclipse-ui0s8haubu {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-y76dksaydk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-y76dksaydk div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
